# Generated by Django 2.2.10 on 2021-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
